# Generated by Django 4.1.2 on 2022-10-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment', models.FloatField(default=0.0)),
                ('shopping', models.FloatField(default=0.0)),
                ('health', models.FloatField(default=0.0)),
                ('food', models.FloatField(default=0.0)),
                ('transportation', models.FloatField(default=0.0)),
                ('education', models.FloatField(default=0.0)),
                ('bills', models.FloatField(default=0.0)),
                ('travel', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('ed', 'Education'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('health', 'Health and Fitness'), ('shopping', 'Shopping'), ('transp', 'Auto and Transportation'), ('travel', 'Travel')], max_length=30)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
